name: Scilab CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get install scilab
    
    - name: Run tests
      run: scilab -nwni -f test.sce
