name: Scilab CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install scilab
      run: sudo apt-get install scilab
    - name: Run tests
      run: scilab -nwni -f test.sce
